"""pizzatype description extension str40

Revision ID: e6123ff0a639
Revises: 40ae859bce90
Create Date: 2025-06-11 15:35:40.217686

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e6123ff0a639'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza_type', 'description',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.String(length=40),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pizza_type', 'description',
                    existing_type=sa.String(length=40),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=False)
    # ### end Alembic commands ###
